# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
  #     desired widget in your `content/home/` folder.
  #   The weight parameter defines the order that the links will appear in.

main:
  - name: About me
    url: /
    weight: 10
  - name: Research
    url: projects/
    weight: 20
  - name: Publication
    url: publication/
    weight: 30
  - name: üç∞ Projects
    url: recipe/
    weight: 40
